### ISSUE TITLE
Implement showing HP/stats as an option

### ISSUE THREAD

**Issue by Kevin-Mok** [Kevin-Mok/gobcog#2]
## Expected Behavior
An option to show the monster's HP/stats.

## Actual Behavior
None currently available.

## Detailed Description
Currently, if I want to know how good the group's chances of beating the monsters are and if it's worth fighting at all, I pull up [`monsters.json`](../tree/master/adventure/data/default/monsters.json) and [`attribs.json`](../tree/master/adventure/data/default/attribs.json) on the side and do some mental math to estimate the final stats. It would be nice to have an option to toggle displaying these stats directly in the monster message. In most RPG's and D&D, you can see the monsters' HP, so I don't why this isn't at least an option you can enable.

## To-Do
- [ ] option to toggle behavior
- [x] show monster stats (HP/diplomacy)
- [x] ~~revert behavior to show HP when running (gives players idea of whether they made right choice)~~
